apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hnr1lcn99-python 
  janus-idp.io/tekton: hnr1lcn99-python
  backstage.io/kubernetes-id: hnr1lcn99-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hnr1lcn99-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  