apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hnr1lcn99-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hnr1lcn99-python 
  name: hnr1lcn99-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hnr1lcn99-python 
